"""
Comprehensive Trip Planning Test - Real Agent Execution with Detailed Output Format
This test executes real agents and formats the output in a comprehensive, story-like manner.
"""

import asyncio
import sys
import os
from pathlib import Path
from datetime import datetime

# Set UTF-8 encoding for Windows console
if sys.platform == 'win32':
    try:
        import codecs
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, errors='replace')
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, errors='replace')
    except:
        pass

# Add parent directory to path for imports
project_root = Path(__file__).resolve().parents[1] / "travelguru-v5" / "backend"
sys.path.insert(0, str(project_root))

from app.agents.langgraph_agents.travel_planner_graph import run_travel_planner, TravelPlannerOrchestrator


def print_separator(char="=", length=100):
    """Print a separator line"""
    print(char * length)


def print_header(query, state):
    """Print the comprehensive trip header"""
    print("\n")
    print_separator("=")
    origin = state.get("origin", "N/A")
    destination = state.get("destination", "N/A")
    start_date = state.get("start_date", "N/A")
    end_date = state.get("end_date", "N/A")
    num_adults = state.get("num_adults", 2)
    
    print(f"  LUXURY TRAVEL: {origin.upper()} -> {destination.upper()} "
          f"({start_date} - {end_date}, {num_adults} Adults)")
    print_separator("=")
    print(f"\nUser Query: {query}\n")


def print_section_header(title):
    """Print a section header"""
    print("\n" + "-"*100)
    print(f"  {title}")
    print("-"*100 + "\n")


def print_subsection(title):
    """Print a subsection separator"""
    print("\n" + "-"*80)
    print(title)
    print("-"*80 + "\n")


def format_short_summary(state):
    """Generate and print comprehensive short summary of the entire trip"""
    print_section_header("SHORT SUMMARY")
    
    # Extract data from state
    origin = state.get("origin", "your city")
    destination = state.get("destination", "destination")
    duration = state.get("duration", 5)
    start_date = state.get("start_date", "")
    num_adults = state.get("num_adults", 2)
    
    # Get composer summary if available
    composer_response = state.get("composer_response", {})
    if isinstance(composer_response, dict):
        summary = composer_response.get("summary", "")
        if summary:
            print(summary)
            return
    
    # Generate comprehensive summary (400-500 words)
    print(f"""
Your {duration}-day journey from {origin} to {destination} promises an unforgettable experience combining 
relaxation, adventure, and cultural exploration. This carefully curated trip is designed to provide the 
perfect balance of activities while ensuring maximum comfort and memorable moments.

[This section should contain 400-500 words describing the complete journey overview including:
- Trip highlights and main experiences
- Hotel details and amenities
- Key attractions and activities planned
- Weather overview and suitability
- Special romantic/family/adventure elements based on trip type
- Return journey details]

Note: Full summary will be generated by the Composer Agent based on all gathered intelligence from 
Flight, Hotel, Places, Weather, and Budget agents.
""".strip())


def format_flight_details(flight):
    """Format a single flight's comprehensive details"""
    # Handle both dict and EnrichedFlight object
    if hasattr(flight, '__dict__'):
        # It's an object, convert to dict-like access
        airline = getattr(flight, "airline", "N/A")
        origin = getattr(flight, "origin", "N/A")
        destination = getattr(flight, "destination", "N/A")
        departure = getattr(flight, "departure_time", "N/A")
        arrival = getattr(flight, "arrival_time", "N/A")
        duration = getattr(flight, "duration", "N/A")
        stops = getattr(flight, "stops", 0)
        price = getattr(flight, "price", 0)
        currency = getattr(flight, "currency", "INR")
        
        # Get enrichment data from EnrichedFlight
        match_score = getattr(flight, "match_score", 0)
        tags = getattr(flight, "tags", [])
        best_for = getattr(flight, "best_for", [])
        timing = getattr(flight, "timing_analysis", None)
        price_intel = getattr(flight, "price_intelligence", None)
        insights = getattr(flight, "insights", [])
        recommendations = getattr(flight, "recommendations", [])
    else:
        # It's a dict
        airline = flight.get("airline", "N/A")
        origin = flight.get("origin", "N/A")
        destination = flight.get("destination", "N/A")
        departure = flight.get("departure_time", "N/A")
        arrival = flight.get("arrival_time", "N/A")
        duration = flight.get("duration", "N/A")
        stops = flight.get("stops", 0)
        price = flight.get("price", 0)
        currency = flight.get("currency", "INR")
        
        # Get enrichment data
        enrichment = flight.get("enrichment", {})
        match_score = enrichment.get("match_score", 0)
        tags = enrichment.get("tags", [])
        best_for = enrichment.get("best_for", [])
        timing = enrichment.get("timing_analysis", {})
        price_intel = enrichment.get("price_intelligence", {})
        insights = enrichment.get("insights", [])
        recommendations = enrichment.get("recommendations", [])
    
    # Format summary
    summary_parts = [
        airline,
        "Direct" if stops == 0 else f"{stops} stop(s)",
        duration,
        f"{currency} {price:,.0f}" if isinstance(price, (int, float)) else str(price)
    ]
    if tags and "cheapest" in [t.lower() for t in tags]:
        summary_parts.append("Cheapest")
    
    print(f"Summary: {' * '.join(summary_parts)}")
    print(f"Match Score: {match_score}/100")
    print(f"Tags: {', '.join(tags) if tags else 'N/A'}")
    print(f"Best For: {', '.join(best_for) if best_for else 'N/A'}")
    
    print("\nFlight Details:")
    print(f"  Airline: {airline}")
    print(f"  Route: {origin} -> {destination}")
    print(f"  Departure: {departure}")
    print(f"  Arrival: {arrival}")
    print(f"  Duration: {duration}")
    print(f"  Stops: {stops}")
    print(f"  Price: {price:,.0f} {currency}" if isinstance(price, (int, float)) else f"  Price: {price} {currency}")
    
    # Handle timing analysis (could be dict or object)
    if timing:
        if hasattr(timing, '__dict__'):
            segment = getattr(timing, 'segment', 'N/A')
            impact = getattr(timing, 'impact', 'N/A')
            suitability = getattr(timing, 'suitability', 'N/A')
        else:
            segment = timing.get('segment', 'N/A') if isinstance(timing, dict) else 'N/A'
            impact = timing.get('impact', 'N/A') if isinstance(timing, dict) else 'N/A'
            suitability = timing.get('suitability', 'N/A') if isinstance(timing, dict) else 'N/A'
        
        print("\nTiming Analysis:")
        print(f"  Time Segment: {segment}")
        print(f"  Impact: {impact}")
        print(f"  Suitability: {suitability}")
    
    # Handle price intelligence (could be dict or object)
    if price_intel:
        if hasattr(price_intel, '__dict__'):
            category = getattr(price_intel, 'category', 'N/A')
            percentile = getattr(price_intel, 'percentile', 'N/A')
            value_score = getattr(price_intel, 'value_score', 'N/A')
            premium = getattr(price_intel, 'premium', 0)
        else:
            category = price_intel.get('category', 'N/A') if isinstance(price_intel, dict) else 'N/A'
            percentile = price_intel.get('percentile', 'N/A') if isinstance(price_intel, dict) else 'N/A'
            value_score = price_intel.get('value_score', 'N/A') if isinstance(price_intel, dict) else 'N/A'
            premium = price_intel.get('premium', 0) if isinstance(price_intel, dict) else 0
        
        print("\nPrice Intelligence:")
        print(f"  Category: {category}")
        print(f"  Percentile: {percentile}")
        print(f"  Value Score: {value_score}/10")
        print(f"  Premium: {premium} {currency} above average")
    
    if insights:
        print("\nIntelligent Insights:")
        for i, insight in enumerate(insights, 1):
            if hasattr(insight, '__dict__'):
                insight_type = getattr(insight, "type", "info")
                message = getattr(insight, "message", "")
            else:
                insight_type = insight.get("type", "info") if isinstance(insight, dict) else "info"
                message = insight.get("message", "") if isinstance(insight, dict) else str(insight)
            print(f"  {i}. [{insight_type}] {message}")
    
    if recommendations:
        print("\nRecommendations:")
        for i, rec in enumerate(recommendations, 1):
            if hasattr(rec, '__dict__'):
                rec_type = getattr(rec, "type", "neutral")
                message = getattr(rec, "message", "")
            else:
                rec_type = rec.get("type", "neutral") if isinstance(rec, dict) else "neutral"
                message = rec.get("message", "") if isinstance(rec, dict) else str(rec)
            print(f"  {i}. [{rec_type}] {message}")


def format_flight_section(flights_data, direction, date_str):
    """Print comprehensive flight options section"""
    if direction == "outbound":
        origin = flights_data.get('origin', 'ORIGIN')
        destination = flights_data.get('destination', 'DESTINATION')
        title = f"FLIGHT OPTIONS: {origin.upper()} TO {destination.upper()} ({date_str.upper()})"
    else:
        origin = flights_data.get('origin', 'ORIGIN')
        destination = flights_data.get('destination', 'DESTINATION')
        title = f"RETURN FLIGHT OPTIONS: {origin.upper()} TO {destination.upper()} ({date_str.upper()})"
    
    print_section_header(title)
    
    # Handle both FlightEnrichmentResult object and plain list
    flights_list = flights_data.get("flights", [])
    if hasattr(flights_list, 'enriched_flights'):
        flights = flights_list.enriched_flights[:3]  # Get enriched flights list
    elif isinstance(flights_list, list):
        flights = flights_list[:3]
    else:
        flights = []
    
    if not flights:
        print("No flights available for this route and date.")
        return
    
    for idx, flight in enumerate(flights, 1):  # Show top 3 flights
        if idx == 1:
            print_subsection(f"FLIGHT #{idx} (RECOMMENDED)")
        else:
            print_subsection(f"FLIGHT #{idx}")
        
        format_flight_details(flight)
        print()


def format_hotel_details(hotel):
    """Format a single hotel's comprehensive details"""
    # Handle both dict and EnrichedHotel object
    if hasattr(hotel, '__dict__'):
        # It's an object
        name = getattr(hotel, "name", "N/A")
        city = getattr(hotel, "city", "N/A")
        address = getattr(hotel, "address", "N/A")
        rating = getattr(hotel, "rating", 0)
        price_per_night = getattr(hotel, "price_per_night", 0)
        currency = getattr(hotel, "currency", "INR")
        amenities = getattr(hotel, "amenities", [])
        checkin = getattr(hotel, "check_in", "N/A")
        checkout = getattr(hotel, "check_out", "N/A")
    else:
        # It's a dict
        name = hotel.get("name", "N/A")
        city = hotel.get("city", "N/A")
        address = hotel.get("address", "N/A")
        rating = hotel.get("rating", 0)
        price_per_night = hotel.get("price_per_night", 0)
        currency = hotel.get("currency", "INR")
        amenities = hotel.get("amenities", [])
        checkin = hotel.get("check_in", "N/A")
        checkout = hotel.get("check_out", "N/A")
    
    # Calculate nights and total cost
    try:
        if checkin != "N/A" and checkout != "N/A":
            checkin_date = datetime.fromisoformat(checkin.replace("Z", ""))
            checkout_date = datetime.fromisoformat(checkout.replace("Z", ""))
            nights = (checkout_date - checkin_date).days
            total_cost = price_per_night * nights if isinstance(price_per_night, (int, float)) else 0
        else:
            nights = 0
            total_cost = 0
    except:
        nights = 0
        total_cost = 0
    
    # Format star rating
    stars = "*" * int(rating) if rating else "N/A"
    
    print(f"{name.upper()} * {stars} * {currency}{price_per_night:,.0f}/night" if isinstance(price_per_night, (int, float)) else f"{name.upper()} * {stars} * {currency}{price_per_night}/night")
    print(f"Address: {address}")
    print(f"Amenities: {', '.join(amenities) if amenities else 'N/A'}")
    print(f"Name: {name.upper()}")
    print(f"City: {city.upper()}")
    print(f"Rating: {stars} ({rating}/5)")
    print(f"Price/Night: {currency}{price_per_night:,.0f}" if isinstance(price_per_night, (int, float)) else f"Price/Night: {currency}{price_per_night}")
    print(f"Stay: {checkin[:10] if checkin != 'N/A' else 'N/A'} to {checkout[:10] if checkout != 'N/A' else 'N/A'}")
    if nights > 0:
        print(f"Total Cost: {currency}{total_cost:,.0f} ({nights} nights)")


def format_hotel_section(hotels_data):
    """Print comprehensive hotel options section"""
    print_section_header("HOTEL OPTIONS")
    
    # Handle both EnrichmentResult object and plain list
    hotels_list = hotels_data.get("hotels", [])
    if hasattr(hotels_list, 'enriched_hotels'):
        hotels = hotels_list.enriched_hotels[:3]  # Get enriched hotels list
    elif isinstance(hotels_list, list):
        hotels = hotels_list[:3]
    else:
        hotels = []
    
    if not hotels:
        print("No hotels available.")
        return
    
    for idx, hotel in enumerate(hotels, 1):  # Show top 3 hotels
        if idx == 1:
            print_subsection(f"HOTEL #{idx}  (RECOMMENDED)")
        else:
            print_subsection(f"HOTEL #{idx}")
        
        format_hotel_details(hotel)
        print()


def format_day_itinerary(day_data, day_number):
    """Format a single day's comprehensive itinerary"""
    date = day_data.get("date", "N/A")
    temperature = day_data.get("temperature", {}).get("avg", "N/A")
    
    # Parse date for day name
    try:
        date_obj = datetime.fromisoformat(date.replace("Z", ""))
        day_name = date_obj.strftime("%A")
        formatted_date = date_obj.strftime("%dTH %B %Y").upper()
    except:
        day_name = ""
        formatted_date = date.upper() if date != "N/A" else "N/A"
    
    print_subsection(f"DAY {day_number}     {formatted_date}     {temperature}°C")
    
    # Day Summary
    print("### SUMMARY OF THE DAY\n")
    day_summary = day_data.get("summary", "")
    if day_summary:
        print(day_summary)
    else:
        print("[Comprehensive 200-300 word summary of the day's activities, key tasks, and highlights will be generated by the Composer Agent]")
    print()
    
    # Get activities by time of day
    activities = day_data.get("activities", {})
    
    # Morning
    morning = activities.get("morning", {})
    if morning:
        start_time = morning.get("start_time", "06:00")
        end_time = morning.get("end_time", "12:00")
        print(f"### MORNING ({start_time} TO {end_time})\n")
        morning_desc = morning.get("description", "")
        if morning_desc:
            print(morning_desc)
        else:
            print("[Comprehensive 400-600 word detailed description of morning activities including flights, hotels, places, transport options, timings, and all relevant details will be generated by the Composer Agent]")
        print()
    
    # Afternoon
    afternoon = activities.get("afternoon", {})
    if afternoon:
        start_time = afternoon.get("start_time", "12:00")
        end_time = afternoon.get("end_time", "18:00")
        print(f"### AFTERNOON ({start_time} TO {end_time})\n")
        afternoon_desc = afternoon.get("description", "")
        if afternoon_desc:
            print(afternoon_desc)
        else:
            print("[Comprehensive 400-600 word detailed description of afternoon activities including flights, hotels, places, transport options, timings, and all relevant details will be generated by the Composer Agent]")
        print()
    
    # Evening
    evening = activities.get("evening", {})
    if evening:
        start_time = evening.get("start_time", "18:00")
        end_time = evening.get("end_time", "23:00")
        print(f"### EVENING ({start_time} TO {end_time})\n")
        evening_desc = evening.get("description", "")
        if evening_desc:
            print(evening_desc)
        else:
            print("[Comprehensive 400-600 word detailed description of evening activities including flights, hotels, places, transport options, timings, and all relevant details will be generated by the Composer Agent]")
        print()


def format_itinerary_section(itinerary_data):
    """Print comprehensive day-by-day itinerary section"""
    print_section_header("DAY-BY-DAY ITINERARY")
    
    days = itinerary_data.get("days", [])
    
    if not days:
        print("No itinerary data available.")
        return
    
    for idx, day in enumerate(days, 1):
        format_day_itinerary(day, idx)


def format_weather_rating(score, rating_label):
    """Convert numeric rating to descriptive text"""
    if score >= 9:
        return f"Exceptional conditions - {rating_label}. Perfect for all planned activities with ideal comfort levels."
    elif score >= 8:
        return f"Excellent conditions - {rating_label}. Very favorable weather with great comfort for most activities."
    elif score >= 7:
        return f"Good conditions - {rating_label}. Pleasant weather suitable for outdoor and indoor activities."
    elif score >= 6:
        return f"Fair conditions - {rating_label}. Acceptable weather with some minor limitations for certain activities."
    elif score >= 5:
        return f"Moderate conditions - {rating_label}. Average weather, plan activities accordingly."
    else:
        return f"Challenging conditions - {rating_label}. Weather may impact some activities, prepare accordingly."


def format_daily_weather(day_weather, date):
    """Format detailed weather for a single day"""
    print_separator("-")
    print(f"DATE: {date}")
    print_separator("-")
    print()
    
    # Weather basics
    condition = day_weather.get("condition", "N/A")
    temp = day_weather.get("temperature", {})
    temp_min = temp.get("min", "N/A")
    temp_max = temp.get("max", "N/A")
    temp_avg = temp.get("avg", "N/A")
    rain_chance = day_weather.get("precipitation_chance", 0)
    
    print("WEATHER:")
    print(f"  Condition: {condition}")
    print(f"  Temperature: {temp_min}C - {temp_max}C (avg {temp_avg}C)")
    print(f"  Rain Chance: {rain_chance}%")
    print()
    
    # Summary
    summary = day_weather.get("summary", "")
    best_time = day_weather.get("best_time", "Anytime during daylight hours")
    print(f"SUMMARY: {summary}")
    print(f"Best Time: {best_time}")
    print()
    
    # Comfort Analysis
    comfort = day_weather.get("comfort_analysis", {})
    overall_score = comfort.get("overall", 0)
    overall_label = comfort.get("overall_label", "N/A")
    temp_score = comfort.get("temperature", 0)
    temp_label = comfort.get("temperature_label", "N/A")
    precip_score = comfort.get("precipitation", 0)
    precip_label = comfort.get("precipitation_label", "N/A")
    description = comfort.get("description", "")
    
    print("COMFORT ANALYSIS:")
    print(f"  Overall: {format_weather_rating(overall_score, overall_label)}")
    print(f"  Temperature: {format_weather_rating(temp_score, temp_label)}")
    print(f"  Precipitation: {format_weather_rating(precip_score, precip_label)}")
    if description:
        print(f"  {description}")
    print()
    
    # Travel Suitability
    suitability = day_weather.get("travel_suitability", {})
    suitability_label = suitability.get("overall", "N/A")
    outdoor = suitability.get("outdoor_activities", {})
    outdoor_score = outdoor.get("score", 0)
    outdoor_label = outdoor.get("label", "N/A")
    sightseeing = suitability.get("sightseeing", {})
    sightseeing_score = sightseeing.get("score", 0)
    sightseeing_label = sightseeing.get("label", "N/A")
    beach = suitability.get("beach_activities", {})
    beach_score = beach.get("score", 0)
    beach_label = beach.get("label", "N/A")
    
    print(f"TRAVEL SUITABILITY: {suitability_label}")
    print(f"  Outdoor Activities: {format_weather_rating(outdoor_score, outdoor_label)}")
    print(f"  Sightseeing: {format_weather_rating(sightseeing_score, sightseeing_label)}")
    print(f"  Beach Activities: {format_weather_rating(beach_score, beach_label)}")
    print()
    
    # Activity Suitability
    best_activities = day_weather.get("best_activities", [])
    if best_activities:
        print("ACTIVITY SUITABILITY:")
        print("  Best Activities:")
        for activity in best_activities:
            print(f"    - {activity}")
        print()
    
    # Risk Assessment
    risks = day_weather.get("risks", [])
    if risks:
        print(f"RISK ASSESSMENT: {', '.join(risks)}")
    else:
        print("RISK ASSESSMENT: none")
    print()
    
    # Packing Advice
    packing = day_weather.get("packing_advice", {})
    recommended = packing.get("recommended", [])
    clothing = packing.get("clothing", [])
    accessories = packing.get("accessories", [])
    
    print("PACKING ADVICE:")
    if recommended:
        print(f"  Recommended: {', '.join(recommended)}")
    if clothing:
        print(f"  Clothing: {', '.join(clothing)}")
    if accessories:
        print(f"  Accessories: {', '.join(accessories)}")
    print()
    
    # Travel Advice
    travel_advice = day_weather.get("travel_advice", "")
    if travel_advice:
        print("TRAVEL ADVICE:")
        print(f"  {travel_advice}")
        print()
    
    # Additional metrics
    wind = day_weather.get("wind", {})
    print("WIND IMPACT:")
    print(f"  Category: {wind.get('category', 'N/A')} ({wind.get('speed', 'N/A')} km/h)")
    print(f"  Impact Score: {wind.get('impact_score', 'N/A')}/10")
    print(f"  {wind.get('description', 'Wind data not available')}")
    print()
    
    humidity = day_weather.get("humidity", {})
    print("HUMIDITY COMFORT:")
    print(f"  Level: {humidity.get('level', 'N/A')} ({humidity.get('value', 'N/A')}%)")
    print(f"  Comfort Score: {humidity.get('comfort_score', 'N/A')}/10")
    print(f"  {humidity.get('description', 'Humidity data not available')}")
    print()
    
    uv = day_weather.get("uv_index", {})
    print("UV INDEX:")
    print(f"  Level: {uv.get('level', 'N/A')} (UV {uv.get('value', 'N/A')})")
    print(f"  Risk: {uv.get('risk', 'N/A')}")
    print(f"  {uv.get('description', 'UV data not available')}")
    print()
    
    aqi = day_weather.get("air_quality", {})
    print("AIR QUALITY:")
    print(f"  AQI: {aqi.get('level', 'N/A')} ({aqi.get('value', 'N/A')})")
    print(f"  Impact: {aqi.get('description', 'Air quality data not available')}")
    print(f"  {aqi.get('advice', 'No air quality restrictions')}")
    print()
    
    # Daily Insights
    insights = day_weather.get("insights", [])
    if insights:
        print("DAILY INSIGHTS:")
        for insight in insights:
            insight_type = insight.get("type", "info")
            message = insight.get("message", "")
            symbol = "[+]" if insight_type == "positive" else "[-]" if insight_type == "negative" else "[!]"
            print(f"  {symbol} {message}")
        print()


def format_weather_section(weather_data):
    """Print comprehensive weather summary and daily breakdown"""
    print_separator("-")
    print("WEATHER SUMMARY")
    print_separator("-")
    print()
    
    # Trip Overview
    overview = weather_data.get("overview", {})
    duration = overview.get("duration", 0)
    avg_temp = overview.get("avg_temperature", 0)
    pleasant_days = overview.get("pleasant_days", 0)
    overall_comfort = overview.get("overall_comfort", "N/A")
    best_day = overview.get("best_day", {})
    worst_day = overview.get("worst_day", {})
    
    print("TRIP OVERVIEW:")
    print(f"  {duration}-day forecast, average {avg_temp}°C, {pleasant_days} pleasant days - {overall_comfort} conditions overall")
    print(f"  Overall Comfort: {overall_comfort}")
    if best_day:
        print(f"  Best Day: {best_day.get('date', 'N/A')} ({best_day.get('reason', 'N/A')})")
    if worst_day:
        print(f"  Worst Day: {worst_day.get('date', 'N/A')} ({worst_day.get('reason', 'N/A')})")
    print()
    
    # Trip Insights
    trip_insights = weather_data.get("trip_insights", [])
    if trip_insights:
        print("TRIP INSIGHTS:")
        for insight in trip_insights:
            insight_type = insight.get("type", "info")
            message = insight.get("message", "")
            symbol = "[+]" if insight_type == "positive" else "[-]" if insight_type == "negative" else "[!]"
            print(f"  {symbol} {message}")
        print()
    
    # Travel Tips
    tips = weather_data.get("travel_tips", [])
    if tips:
        print("TRAVEL TIPS:")
        for tip in tips:
            print(f"  - {tip}")
        print()
    
    # Packing Checklist
    packing = weather_data.get("packing_checklist", {})
    if packing:
        print("PACKING CHECKLIST:")
        for category, items in packing.items():
            print(f"  [ ] === {category.upper()} ===")
            for item in items:
                print(f"  [ ] {item}")
        print()
    
    # Daily Breakdown
    print_separator("=")
    print("DAILY WEATHER BREAKDOWN")
    print_separator("=")
    print()
    
    daily_forecasts = weather_data.get("daily_forecasts", [])
    for day_data in daily_forecasts:
        date = day_data.get("date", "N/A")
        format_daily_weather(day_data, date)


def format_budget_section(budget_data):
    """Print comprehensive budget summary and analysis"""
    print_separator("-")
    print("BUDGET SUMMARY")
    print_separator("-")
    print()
    
    # Basic Summary
    print("BASIC BUDGET SUMMARY")
    print_separator("-")
    
    flights_cost = budget_data.get("flights_cost", 0)
    hotel_cost = budget_data.get("hotel_cost", 0)
    activities_cost = budget_data.get("activities_cost", 0)
    total_cost = budget_data.get("total_cost", 0)
    currency = budget_data.get("currency", "INR")
    
    print(f"Flights Cost:    {currency} {flights_cost:,.0f}" if isinstance(flights_cost, (int, float)) else f"Flights Cost:    {currency} {flights_cost}")
    print(f"Hotel Cost:      {currency} {hotel_cost:,.0f}" if isinstance(hotel_cost, (int, float)) else f"Hotel Cost:      {currency} {hotel_cost}")
    print(f"Activities Cost: {currency} {activities_cost:,.0f}" if isinstance(activities_cost, (int, float)) else f"Activities Cost: {currency} {activities_cost}")
    print(f"Total Cost:      {currency} {total_cost:,.0f}" if isinstance(total_cost, (int, float)) else f"Total Cost:      {currency} {total_cost}")
    print(f"Currency:        {currency}")
    print()
    
    # Enrichment Details
    print_separator("=")
    print("ENRICHMENT DETAILS")
    print_separator("=")
    print()
    
    # Verdict
    verdict = budget_data.get("verdict", "")
    if verdict:
        print("VERDICT:")
        print_separator("-")
        print(verdict)
        print()
    
    # Budget Health Score
    health_score = budget_data.get("health_score", {})
    if health_score:
        score_value = health_score.get("score", 0)
        score_label = health_score.get("label", "N/A")
        factors = health_score.get("factors", [])
        
        print("BUDGET HEALTH SCORE:")
        print_separator("-")
        print(f"Score: {score_value} / 10 ({score_label})")
        print()
        if factors:
            print("Based on:")
            for factor in factors:
                print(f"  - {factor}")
            print()
    
    # Full Cost Breakdown
    breakdown = budget_data.get("full_breakdown", {})
    if breakdown:
        print("FULL COST BREAKDOWN:")
        print_separator("-")
        for category, amount in breakdown.items():
            if isinstance(amount, (int, float)):
                print(f"{category.replace('_', ' ').title():20} {currency} {amount:,.0f}")
            else:
                print(f"{category.replace('_', ' ').title():20} {currency} {amount}")
        print("                    " + "-"*20)
        estimated_total = breakdown.get("total_estimated", total_cost)
        print(f"{'TOTAL ESTIMATED':20} {currency} {estimated_total:,.0f}" if isinstance(estimated_total, (int, float)) else f"{'TOTAL ESTIMATED':20} {currency} {estimated_total}")
        print()
    
    # Intelligence Metrics
    metrics = budget_data.get("intelligence_metrics", {})
    if metrics:
        print("INTELLIGENCE METRICS:")
        print_separator("-")
        cost_per_day = metrics.get("cost_per_day", 0)
        cost_per_person = metrics.get("cost_per_person", 0)
        dominant_driver = metrics.get("dominant_driver", "N/A")
        distribution = metrics.get("category_distribution", {})
        
        print(f"Cost per Day:    {currency} {cost_per_day:,.2f}" if isinstance(cost_per_day, (int, float)) else f"Cost per Day:    {currency} {cost_per_day}")
        print(f"Cost per Person: {currency} {cost_per_person:,.2f}" if isinstance(cost_per_person, (int, float)) else f"Cost per Person: {currency} {cost_per_person}")
        print(f"Dominant Driver: {dominant_driver}")
        print()
        
        if distribution:
            print("Category Distribution:")
            for category, percentage in distribution.items():
                bar_length = int(percentage / 2) if isinstance(percentage, (int, float)) else 0
                bar = "#" * bar_length
                print(f"  {category:20} {percentage:5.1f}% {bar}" if isinstance(percentage, (int, float)) else f"  {category:20} {percentage}% {bar}")
            print()
    
    # Trip Classification
    classification = budget_data.get("trip_classification", {})
    if classification:
        print("TRIP CLASSIFICATION:")
        print_separator("-")
        trip_type = classification.get("type", "N/A")
        threshold = classification.get("threshold", "N/A")
        print(f"Type:       {trip_type}")
        print(f"Threshold:  {threshold}")
        print()
    
    # Issues Detected
    issues = budget_data.get("issues", [])
    if issues:
        print(f"ISSUES DETECTED ({len(issues)}):")
        print_separator("-")
        for issue in issues:
            severity = issue.get("severity", "INFO")
            title = issue.get("title", "")
            description = issue.get("description", "")
            impact = issue.get("impact", "")
            
            print(f"[{severity}] {title}")
            print(f"  {description}")
            if impact:
                print(f"  Impact: {currency} {impact:,.0f}" if isinstance(impact, (int, float)) else f"  Impact: {currency} {impact}")
            print()
    
    # Recommendations
    recommendations = budget_data.get("recommendations", [])
    if recommendations:
        print(f"RECOMMENDATIONS ({len(recommendations)}):")
        print_separator("-")
        for idx, rec in enumerate(recommendations, 1):
            priority = rec.get("priority", "MEDIUM")
            category = rec.get("category", "N/A")
            action = rec.get("action", "")
            savings = rec.get("savings", 0)
            
            print(f"{idx}. [{priority}] {category.upper()}")
            print(f"   Action: {action}")
            if savings:
                print(f"   Savings: {currency} {savings:,.0f}" if isinstance(savings, (int, float)) else f"   Savings: {currency} {savings}")
            print()
    
    # Simulation
    simulation = budget_data.get("simulation", {})
    if simulation:
        print()
        print("SIMULATION - If you apply top recommendations:")
        print_separator("=")
        print()
        
        applied_recs = simulation.get("applied_recommendations", [])
        original_total = simulation.get("original_total", 0)
        total_savings = simulation.get("total_savings", 0)
        new_total = simulation.get("new_total", 0)
        status = simulation.get("status", "")
        
        print(f"Applying {len(applied_recs)} recommendation(s):")
        for idx, rec in enumerate(applied_recs, 1):
            print(f"  {idx}. {rec}")
        print()
        
        print(f"Original Total:      {currency} {original_total:,.0f}" if isinstance(original_total, (int, float)) else f"Original Total:      {currency} {original_total}")
        print(f"Total Savings:       {currency} {total_savings:,.0f}" if isinstance(total_savings, (int, float)) else f"Total Savings:       {currency} {total_savings}")
        print(f"New Estimated Total: {currency} {new_total:,.0f}" if isinstance(new_total, (int, float)) else f"New Estimated Total: {currency} {new_total}")
        print()
        print(f"Status: {status}")
        print()


def format_recommendations_section(recommendations_data):
    """Print comprehensive recommendations and tips"""
    print_section_header("RECOMMENDATIONS & TIPS")
    
    recommendations = recommendations_data.get("recommendations", [])
    
    if not recommendations:
        print("No specific recommendations available. General tips:")
        recommendations = [
            "Book flights and hotels in advance for better rates and availability",
            "Check visa requirements and passport validity well before departure",
            "Purchase comprehensive travel insurance covering medical emergencies and trip cancellations",
            "Keep digital and physical copies of important documents (passport, tickets, hotel bookings)",
            "Research local customs, dress codes, and cultural norms of your destination",
            "Register with your embassy if traveling internationally for extended periods",
            "Pack essential medications and a basic first-aid kit for emergencies",
            "Download offline maps and translation apps for areas with limited connectivity",
            "Inform your bank about travel plans to avoid card blocks in foreign locations",
            "Exchange some currency before departure for immediate expenses upon arrival",
            "Keep emergency contact numbers saved, including local police and medical services",
            "Use hotel safes for valuables and avoid carrying large amounts of cash",
            "Stay hydrated, especially in hot climates, and be mindful of food hygiene",
            "Arrive at airports at least 2-3 hours early for international flights",
            "Check weather forecasts regularly and pack accordingly with layers and rain protection"
        ]
    
    for idx, rec in enumerate(recommendations, 1):
        if isinstance(rec, dict):
            tip_text = rec.get("tip", rec.get("recommendation", ""))
            category = rec.get("category", "")
            if category:
                print(f"{idx}. [{category}] {tip_text}")
            else:
                print(f"{idx}. {tip_text}")
        else:
            print(f"{idx}. {rec}")
    print()


def format_thankyou_section():
    """Print thank you note"""
    print_section_header("THANK YOU NOTE")
    
    thankyou = """
Thank you for choosing our travel planning service to craft your perfect getaway! We've poured our
expertise and attention to detail into creating this comprehensive itinerary tailored specifically
for your preferences and requirements.

Your journey has been meticulously planned to ensure every moment is memorable, comfortable, and
stress-free. From selecting the best flight options that balance convenience and value, to handpicking
accommodations that match your style and budget, we've considered every aspect of your travel experience.

The day-by-day itinerary has been carefully structured to provide the perfect balance between exploration
and relaxation, ensuring you experience the destination's highlights while maintaining a comfortable pace.
We've factored in weather conditions, local insights, and timing recommendations to help you make the most
of each day.

As you embark on this adventure, remember that flexibility is key to enjoying any journey. While we've
provided detailed plans and recommendations, feel free to adapt them based on your mood and discoveries
along the way. Some of the best travel memories come from unexpected detours and spontaneous decisions.

Please review the budget breakdown and recommendations carefully to optimize your travel expenses. The
weather section will help you pack appropriately and plan outdoor activities for the best conditions.
Don't hesitate to use the comprehensive tips we've provided - they're designed to help you navigate
common travel challenges with ease.

We wish you an absolutely wonderful trip filled with amazing experiences, beautiful memories, and safe
travels. May this journey exceed your expectations and leave you with stories to share for years to come.

Bon voyage and happy travels!

"""
    print(thankyou.strip())
    print()


def run_trip_planning_test():
    """Execute the full trip planning workflow and display results"""
    
    # User query
    user_query = "Create a 5 day romantic plan for 2 adults from 12 Feb 2026 from Delhi to Goa"
    
    print("\n" + "="*100)
    print(" >> STARTING COMPREHENSIVE TRIP PLANNING TEST")
    print("="*100)
    print(f"\nUser Query: {user_query}\n")
    print("Executing agents and gathering data...")
    print()
    
    try:
        # Create orchestrator and get full response
        orchestrator = TravelPlannerOrchestrator()
        result = orchestrator.plan_trip_from_text(user_query)
        
        # Extract structured data
        trip_response = result.get("trip")
        narrative = result.get("narrative")
        debug = result.get("debug", {})
        enriched = debug.get("enriched", {})
        
        print("\n" + "="*100)
        print(" >> COMPOSER AGENT OUTPUT (Multi-Pass Comprehensive Narrative)")
        print("="*100)
        print()
        
        # Print the Composer's full narrative (6000-9000 words)
        if narrative:
            print(narrative)
        else:
            print("ERROR: No narrative generated by Composer Agent")
        
        # Print metrics
        print("\n" + "="*100)
        print(" >> OUTPUT METRICS")
        print("="*100)
        if narrative:
            word_count = len(narrative.split())
            char_count = len(narrative)
            print(f"  Total Words:      {word_count:,}")
            print(f"  Total Characters: {char_count:,}")
            print(f"  Target Range:     6,000 - 9,000 words (for 5-day trip)")
            print()
            if 6000 <= word_count <= 9000:
                print(f"  STATUS: ✓ SUCCESS - Output is {word_count:,} words (within target)")
            elif word_count < 6000:
                print(f"  STATUS: ~ PARTIAL - Output is {word_count:,} words (needs +{6000-word_count:,} more)")
            else:
                print(f"  STATUS: ✓ EXCELLENT - Output is {word_count:,} words ({int((word_count/6000)*100)}% of minimum target)")
        
        print("="*100)
        print(" >> COMPREHENSIVE TRAVEL PLAN GENERATED SUCCESSFULLY")
        print("="*100)
        print()
        
    except Exception as e:
        print(f"\n >> ERROR during trip planning: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    run_trip_planning_test()



